name: desktop_translation_linux
description: Desktop translation tool for linux.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # 添加以下两行
  flutter_localizations:
    sdk: flutter
  file_picker: ^6.2.0
  path_provider: ^2.1.3
  desktop_window: ^0.4.0
  flutter_platform_alert: ^0.6.1
  camera: ^0.10.5
  flutter_sound: ^9.2.13
  clipboard: ^0.1.3
  http: ^0.13.3
  shared_preferences: ^2.2.0
  encrypt: ^5.0.1
  dart_openai: ^1.8.4
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3
  mime: ^1.0.4  # 用于文件类型检测
  window_manager: ^0.3.0  # 用于窗口管理 (最小化、最大化、还原、关闭)

  # Linux specific dependencies
  path_provider_linux: ^2.2.1
  shared_preferences_linux: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
